const CHANGE_TOP_BANNERS = 'recommend/CHANGE_TOP_BANNERS';
const CHANGE_HOT_RECOMMEND = 'recommend/CHANGE_HOT_RECOMMEND';
const CHANGE_NEW_ALBUM = 'recommend/CHANGE_NEW_ALBUM';

const CHANGE_UP_RANKING = 'recommend/CHANGE_UP_RANKING';
const CHANGE_NEW_RANKING = 'recommend/CHANGE_NEW_RANKING';
const CHANGE_ORIGIN_RANKING = 'recommend/CHANGE_ORIGIN_RANKING';

export {
  CHANGE_TOP_BANNERS,
  CHANGE_HOT_RECOMMEND,
  CHANGE_NEW_ALBUM,
  CHANGE_UP_RANKING,
  CHANGE_NEW_RANKING,
  CHANGE_ORIGIN_RANKING,
};
