const CHANGE_TOP_BANNERS = 'recommend/CHANGE_TOP_BANNERS';
const CHANGE_HOT_RECOMMEND = 'recommend/CHANGE_HOT_RECOMMEND';
const CHANGE_NEW_ALBUM = 'recommend/CHANGE_NEW_ALBUM';

export { CHANGE_TOP_BANNERS, CHANGE_HOT_RECOMMEND, CHANGE_NEW_ALBUM };
