const Add_ITEM_TO_PLAY_MUSICS_LIST = 'player/Add_ITEM_TO_PLAY_MUSICS_LIST'; // 添加歌曲到播放列表
const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX';

export { Add_ITEM_TO_PLAY_MUSICS_LIST, CHANGE_CURRENT_SONG_INDEX };
