const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG'; // 获取当前歌曲信息
const Add_ITEM_TO_PLAY_MUSICS_LIST = 'player/Add_ITEM_TO_PLAY_MUSICS_LIST'; // 添加歌曲到播放列表
const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX';

export {
  CHANGE_CURRENT_SONG,
  Add_ITEM_TO_PLAY_MUSICS_LIST,
  CHANGE_CURRENT_SONG_INDEX,
};
