const Add_ITEM_TO_PLAY_MUSICS_LIST = 'player/Add_ITEM_TO_PLAY_MUSICS_LIST'; // 添加歌曲到播放列表
const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'; // 当前播放歌曲索引值
const CHANGE_CURRENT_SONG_LYRICS = 'player/CHANGE_CURRENT_SONG_LYRICS';

export {
  Add_ITEM_TO_PLAY_MUSICS_LIST,
  CHANGE_CURRENT_SONG_INDEX,
  CHANGE_CURRENT_SONG_LYRICS,
};
