const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'; // 当前播放歌曲索引值
const CHANGE_CURRENT_SONG_LYRICS = 'player/CHANGE_CURRENT_SONG_LYRICS'; // 当前歌曲歌词
const CHANGE_PLAY_MUSIC_LIST = 'play/CHANGE_PLAY_MUSIC_LIST'; // 当前歌曲播放列表
const CHANGE_PLAY_SEQUENCE = 'play/CHANGE_PLAY_SEQUENCE'; // 播放顺序
const CHANGE_CURRENT_SONG = 'play/CHANGE_CURRENT_SONG'; // 当前播放歌曲
const CHANGE_CURRENT_LYRIC_INDEX = 'play/CHANGE_CURRENT_LYRIC_INDEX'; // 当前歌词索引

// 列表播放顺序
const SEQUENCE_ORDER = 0; // 列表循环
const SEQUENCE_LOOP = 1; // 单曲循环
const SEQUENCE_RANDOM = 2; // 随机播放

export {
  CHANGE_CURRENT_SONG_INDEX,
  CHANGE_CURRENT_SONG_LYRICS,
  CHANGE_PLAY_MUSIC_LIST,
  CHANGE_PLAY_SEQUENCE,
  CHANGE_CURRENT_SONG,
  CHANGE_CURRENT_LYRIC_INDEX,
  SEQUENCE_ORDER,
  SEQUENCE_LOOP,
  SEQUENCE_RANDOM,
};
